### ISSUE TITLE
BE Server chashes without handling arduino bad json

### ISSUE THREAD

**Issue by husseinodeh** [CxGarcia/thesis-project#60]
```
MQTT client connected
MQTT client connected
MQTT client connected
[Nest] 19798   - 03/25/2021, 11:17:44 AM   [ActionGateway] Client connected: ZtuTe8lltqwIm-zmAAAA
{ id: 'pump1', action: 'off', duration: 0 }
[Nest] 19798   - 03/25/2021, 11:17:44 AM   [ActionGateway] Duration received: [object Object]
action { id: 'pump1', action: 'off', duration: 0 }
Successfully published message to topic: action
undefined:1
Connection established #pump1
^

SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.statusUpdateHandler (/home/hussein/Codeworks/thesis-project/server/dist/action/action.service.js:36:35)
    at MqttClient.emit (node:events:388:22)
    at MqttClient._handlePublish (/home/hussein/Codeworks/thesis-project/server/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/home/hussein/Codeworks/thesis-project/server/node_modules/mqtt/lib/client.js:410:12)
    at work (/home/hussein/Codeworks/thesis-project/server/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/home/hussein/Codeworks/thesis-project/server/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/home/hussein/Codeworks/thesis-project/server/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/hussein/Codeworks/thesis-project/server/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/home/hussein/Codeworks/thesis-project/server/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
```

**Comment by husseinodeh** [comment]
it happens when it receives ```Connection established #pump1``` as a string in the action topic
